"use client";
import { useState } from "react";

interface EditState { revision: number; title: string; occurredOn: string; summary: string; ownership: string | null; impacts: Array<{ id?: string; description: string }>; evidence: Array<{ id?: string; label: string; noteOrExcerpt: string | null; url: string | null }>; themes: Array<{ themeId: string; rationale: string; strength: 1 | 2 }> }
export function ApprovedExperienceEditor({ experienceId, initial, vocabulary }: { experienceId: string; initial: EditState; vocabulary: Array<{ slug: string; name: string; id?: string }> }) {
  const [edit, setEdit] = useState(initial); const [state, setState] = useState<"idle" | "saving" | "saved" | "conflict" | "error">("idle");
  async function save() { setState("saving"); const response = await fetch(`/api/experiences/${experienceId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(edit) }); const payload = await response.json(); if (response.status === 409) return setState("conflict"); if (!response.ok) return setState("error"); setEdit((current) => ({ ...current, revision: payload.data.revision })); setState("saved"); }
  function toggleTheme(themeId: string) { setEdit((current) => current.themes.some((item) => item.themeId === themeId) ? { ...current, themes: current.themes.filter((item) => item.themeId !== themeId) } : { ...current, themes: [...current.themes, { themeId, strength: 1, rationale: "User selected this theme during record review." }] }); }
  return <section className="review-card"><p className="card-label">Edit approved record</p><h2>Update your accepted facts and conclusions</h2><p>Changes keep their source history and recalculate Career Evolution from approved data.</p><label>Title<input value={edit.title} onChange={(event) => setEdit({ ...edit, title: event.target.value })}/></label><label>Date<input type="date" value={edit.occurredOn} onChange={(event) => setEdit({ ...edit, occurredOn: event.target.value })}/></label><label>Summary<textarea rows={4} value={edit.summary} onChange={(event) => setEdit({ ...edit, summary: event.target.value })}/></label><label>Ownership<textarea rows={3} value={edit.ownership ?? ""} onChange={(event) => setEdit({ ...edit, ownership: event.target.value || null })}/></label>{edit.impacts.map((impact, index) => <label key={impact.id ?? index}>Impact {index + 1}<textarea value={impact.description} onChange={(event) => setEdit({ ...edit, impacts: edit.impacts.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item) })}/></label>)}{edit.evidence.map((evidence, index) => <div key={evidence.id ?? index}><label>Evidence label<input value={evidence.label} onChange={(event) => setEdit({ ...edit, evidence: edit.evidence.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item) })}/></label><label>Evidence note<textarea value={evidence.noteOrExcerpt ?? ""} onChange={(event) => setEdit({ ...edit, evidence: edit.evidence.map((item, itemIndex) => itemIndex === index ? { ...item, noteOrExcerpt: event.target.value || null } : item) })}/></label><label>HTTPS evidence link<input type="url" value={evidence.url ?? ""} onChange={(event) => setEdit({ ...edit, evidence: edit.evidence.map((item, itemIndex) => itemIndex === index ? { ...item, url: event.target.value || null } : item) })}/></label></div>)}<fieldset><legend>Accepted themes</legend>{vocabulary.map((theme) => theme.id ? <label className="checkbox-row" key={theme.id}><input type="checkbox" checked={edit.themes.some((item) => item.themeId === theme.id)} onChange={() => toggleTheme(theme.id!)}/>{theme.name}</label> : null)}</fieldset><button className="primary-action" disabled={state === "saving" || state === "conflict"} onClick={save} type="button">{state === "saving" ? "Saving…" : "Save approved record"}</button><p role="status">{state === "saved" ? "Approved record saved. Evolution is updated." : state === "conflict" ? "A newer version exists. Your edits remain here; reload before retrying." : state === "error" ? "Review the fields and HTTPS links." : ""}</p></section>;
}
