"use client";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { ExperienceExtraction } from "@/lib/ai/extraction-schema";

export function ReviewEditor({ draftId, initialDraft, initialRevision, generationMode }: { draftId: string; initialDraft: ExperienceExtraction; initialRevision: number; generationMode: "live" | "fixture" }) {
  const router = useRouter(); const [draft, setDraft] = useState(initialDraft); const [revision, setRevision] = useState(initialRevision);
  const [saveState, setSaveState] = useState<"saved" | "saving" | "conflict" | "error">("saved"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const dirty = useRef(false); const savedSnapshot = useRef(JSON.stringify(initialDraft));
  const impact = draft.impacts[0]; const theme = draft.themes[0];
  async function save() { setSaveState("saving"); const response = await fetch(`/api/drafts/${draftId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draft, revision }) }); const payload = await response.json(); if (response.status === 409) { setSaveState("conflict"); throw new Error(payload.error.message); } if (!response.ok) { setSaveState("error"); throw new Error("Review the draft fields before continuing."); } setRevision(payload.data.revision); setSaveState("saved"); dirty.current = false; savedSnapshot.current = JSON.stringify(draft); return payload.data.revision as number; }
  // Saving depends on the edited draft only; revision updates must not schedule another save.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (JSON.stringify(draft) === savedSnapshot.current) return; dirty.current = true; const timer = window.setTimeout(() => save().catch((caught) => setError(caught instanceof Error ? caught.message : "Autosave failed.")), 700); return () => window.clearTimeout(timer); }, [draft]);
  function updateExperience(field: "title" | "occurredOn" | "summary" | "ownership", value: string) { setDraft((current) => ({ ...current, experience: { ...current.experience, [field]: value || (field === "ownership" ? null : value) } })); }
  async function approve() { setBusy(true); setError(null); try { const currentRevision = dirty.current ? await save() : revision; const response = await fetch(`/api/drafts/${draftId}/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ revision: currentRevision }) }); if (!response.ok) throw new Error("The draft was not added."); router.push("/"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Approval failed"); setBusy(false); } }
  async function discard() { setBusy(true); await fetch(`/api/drafts/${draftId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "reject" }) }); router.push("/"); router.refresh(); }
  const saveMessage = saveState === "saving" ? "Saving changes…" : saveState === "saved" ? "All changes saved" : saveState === "conflict" ? "Newer server version found. Your edits are preserved; reload before retrying." : "Could not save changes.";
  return <div className="review-layout"><p className={`save-state save-${saveState}`} role="status">{saveMessage}</p>
    <section className="review-card"><div className="review-heading"><div><p className="card-label">User-provided facts</p><h2>Experience</h2></div><span className="source-badge source-user_report">User reported</span></div><label>Title<input value={draft.experience.title} onChange={(event) => updateExperience("title", event.target.value)}/></label><label>Date<input type="date" value={draft.experience.occurredOn} onChange={(event) => updateExperience("occurredOn", event.target.value)}/></label><label>Summary<textarea rows={5} value={draft.experience.summary} onChange={(event) => updateExperience("summary", event.target.value)}/></label><label>Ownership<textarea rows={3} value={draft.experience.ownership ?? ""} onChange={(event) => updateExperience("ownership", event.target.value)}/></label></section>
    {impact ? <section className="review-card"><p className="card-label">Reported outcome</p><h2>Impact</h2><label>Description<textarea rows={4} value={impact.description} onChange={(event) => setDraft((current) => ({ ...current, impacts: [{ ...impact, description: event.target.value }] }))}/></label></section> : null}
    <section className="review-card"><p className="card-label">Supporting material · optional</p><h2>Evidence note</h2><label>Label<input value={draft.evidence?.label ?? ""} onChange={(event) => setDraft((current) => ({ ...current, evidence: { label: event.target.value, noteOrExcerpt: current.evidence?.noteOrExcerpt ?? "", url: current.evidence?.url ?? "" } }))}/></label><label>Note or excerpt<textarea rows={3} value={draft.evidence?.noteOrExcerpt ?? ""} onChange={(event) => setDraft((current) => ({ ...current, evidence: { label: current.evidence?.label ?? "Supporting note", noteOrExcerpt: event.target.value, url: current.evidence?.url ?? "" } }))}/></label></section>
    {theme ? <section className="review-card interpretation-card"><p className="card-label">AI interpretation</p><div className="badge-row"><span className="source-badge source-ai_interpretation">{generationMode === "live" ? "Live AI suggestion" : "Fixture suggestion"}</span><span className="source-badge">Not verified fact</span></div><h2>{theme.themeSlug.replaceAll("-", " ")}</h2><label>Why it may fit<textarea rows={3} value={theme.rationale} onChange={(event) => setDraft((current) => ({ ...current, themes: [{ ...theme, rationale: event.target.value }] }))}/></label><p>{draft.interpretation.text}</p><p className="uncertainty">Uncertainty: {draft.interpretation.uncertainty}</p></section> : null}
    <div className="approval-bar"><div><strong>You are the final authority.</strong><span>Approval adds these reviewed fields to your Career Record.</span></div><div className="action-row"><button className="text-action" disabled={busy} onClick={discard} type="button">Discard</button><button className="primary-action" disabled={busy || saveState === "conflict"} onClick={approve} type="button">{busy ? "Adding…" : "Add to Career Record"}</button></div></div>{error ? <p className="form-error" role="alert">{error}</p> : null}</div>;
}
