import Link from "next/link";
import type { CareerEvolutionView } from "@/lib/domain/career-evolution";

const bandY = { "Well supported": 24, Recurring: 72, Emerging: 120, "No evidence": 168 } as const;

export function EvolutionChart({ evolution }: { evolution: CareerEvolutionView }) {
  if (!evolution.themes.length) return <p>No approved theme evidence yet.</p>;
  const width = Math.max(520, evolution.quarters.length * 120);
  return <div className="evolution-stack">{evolution.themes.map((theme) => <section className="evolution-theme" id={theme.slug} key={theme.id}><h2>{theme.name}</h2><div className="chart-scroll"><svg aria-label={`${theme.name} approved evidence trend`} role="img" viewBox={`0 0 ${width} 210`}><title>{`${theme.name} approved Career Record evidence by quarter`}</title>{Object.entries(bandY).map(([label, y]) => <g key={label}><line x1="110" x2={width - 20} y1={y} y2={y} className="chart-grid"/><text x="4" y={y + 4}>{label}</text></g>)}{theme.points.map((point, index) => { const x = 130 + index * 110; const y = bandY[point.band]; return <g key={point.quarter}><text x={x - 22} y="202">{point.quarter}</text>{point.experienceCount ? <Link href={`#${theme.slug}-${point.quarter.replace(" ", "-")}`} aria-label={`${theme.name}, ${point.quarter}: ${point.band}, ${point.experienceCount} supporting experiences`}><circle className="chart-point" cx={x} cy={y} r="9"><title>{`${point.band}; ${point.experienceCount} supporting experiences; evidence weight ${point.evidenceWeight}`}</title></circle></Link> : <circle className="chart-empty" cx={x} cy={y} r="5"/>}</g>;})}</svg></div><table><caption>{theme.name} evidence table</caption><thead><tr><th>Quarter</th><th>Band</th><th>Evidence points</th><th>Experiences</th></tr></thead><tbody>{theme.points.map((point) => <tr key={point.quarter}><th>{point.quarter}</th><td>{point.band}</td><td>{point.evidenceWeight}</td><td>{point.experienceCount}</td></tr>)}</tbody></table><div className="supporting-list">{theme.points.filter((point) => point.experienceCount).map((point) => <section id={`${theme.slug}-${point.quarter.replace(" ", "-")}`} key={point.quarter}><h3>{point.quarter} supporting records</h3>{theme.supportingRecords.filter((record) => record.quarter === point.quarter).map((record) => <article key={record.experienceId}><Link href={`/experiences/${record.experienceId}`}>{record.title}</Link><p>{record.rationale}</p><span className="source-badge source-ai_interpretation">{record.sourceKind.replaceAll("_", " ")}</span></article>)}</section>)}</div></section>)}</div>;
}
