"use client";
import { useState } from "react";
import type { PromotionPacketDraft } from "@/lib/ai/schemas";

interface Option { id: string; title: string; occurred_on: string; summary: string; confidence: string }
export function PromotionBuilder({ options, initialAsset }: { options: Option[]; initialAsset: { id: string; draft: PromotionPacketDraft; mode: string } | null }) {
  const [selected, setSelected] = useState<string[]>(initialAsset ? [...new Set(initialAsset.draft.claims.flatMap((claim) => claim.sourceIds))] : []); const [targetRole, setTargetRole] = useState("");
  const [assetId, setAssetId] = useState(initialAsset?.id ?? null); const [draft, setDraft] = useState<PromotionPacketDraft | null>(initialAsset?.draft ?? null); const [mode, setMode] = useState(initialAsset?.mode ?? null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const titles = new Map(options.map((option) => [option.id, option.title]));
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < 4 ? [...current, id] : current); }
  async function generate() { setBusy(true); setMessage(null); const response = await fetch("/api/assets/promotion-packet", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ experienceIds: selected, targetRole: targetRole || undefined }) }); const payload = await response.json(); setBusy(false); if (!response.ok) return setMessage(payload.error?.message ?? "Generation failed."); setAssetId(payload.data.assetId); setDraft(payload.data.draft); setMode(payload.data.generationMode); window.history.replaceState(null, "", `/assets/promotion?asset=${payload.data.assetId}`); }
  async function save(status: "draft" | "final") { if (!assetId || !draft) return; setBusy(true); const response = await fetch(`/api/assets/${assetId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draft, status }) }); setBusy(false); setMessage(response.ok ? status === "final" ? "Packet finalized." : "Draft saved." : "Could not save grounded edits."); }
  return <div className="asset-layout"><section className="review-card"><p className="card-label">1 · Choose approved sources</p><h2>Select two to four experiences</h2><div className="source-selector">{options.map((option) => <label key={option.id}><input checked={selected.includes(option.id)} onChange={() => toggle(option.id)} type="checkbox"/><span><strong>{option.title}</strong><small>{option.occurred_on} · {option.confidence.replaceAll("_", " ")}</small></span></label>)}</div><label>Target role (optional)<input value={targetRole} onChange={(event) => setTargetRole(event.target.value)} placeholder="Staff Engineer"/></label><button className="primary-action" disabled={busy || selected.length < 2 || selected.length > 4} onClick={generate} type="button">{busy ? "Building grounded packet…" : "Generate promotion section"}</button></section>{draft ? <section className="asset-draft"><div className="badge-row"><span className="source-badge source-ai_interpretation">{mode === "live" ? "Live AI draft" : mode === "template" ? "Deterministic template" : "Demo fixture response"}</span><span className="source-badge">Editable draft</span></div><label>Heading<input value={draft.heading} onChange={(event) => setDraft({ ...draft, heading: event.target.value })}/></label><label>Summary<textarea rows={3} value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })}/></label>{draft.claims.map((claim, index) => <article className="claim-card" key={claim.id}><label>Claim {index + 1}<textarea rows={5} value={claim.text} onChange={(event) => setDraft({ ...draft, claims: draft.claims.map((item) => item.id === claim.id ? { ...item, text: event.target.value } : item) })}/></label><div className="badge-row"><span className={`source-badge confidence-${claim.evidenceState === "user_reported" ? "reported" : claim.evidenceState}`}>{claim.evidenceState.replaceAll("_", " ")}</span>{claim.sourceIds.map((sourceId) => <a className="citation-chip" href={`/experiences/${sourceId}`} target="_blank" rel="noreferrer" key={sourceId}>Source: {titles.get(sourceId) ?? "Approved experience"}</a>)}</div></article>)}{draft.gaps.length ? <aside className="evidence-gaps"><h2>Evidence gaps</h2>{draft.gaps.map((gap) => <p key={gap.text}>{gap.text}</p>)}</aside> : null}<div className="action-row"><button className="text-action" disabled={busy} onClick={() => save("draft")} type="button">Save draft</button><button className="primary-action" disabled={busy} onClick={() => save("final")} type="button">Finalize packet</button></div></section> : null}{message ? <p role="status">{message}</p> : null}</div>;
}
